language: node_js
node_js:
  - 12
sudo: required
services:
  - docker
before_install:
  - docker build -t alessar13/docker-react-travis -f Dockerfile.dev .
script:
  - docker run -e CI=true alessar13/docker-react-travis npm run test